name: Update gist with Chess.com Ratings
on:
  push:
    branches: master
  schedule:
    - cron: "0 */2 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Update gist
        run: python chess_com_box.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          CHESS_COM_USERNAME: ${{ secrets.CHESS_COM_USERNAME }}
